export function generateReadme(repoData: any): string {
    const { meta, languages, packageJson } = repoData;
    let readme = `# ${meta.name}\n\n${meta.description || 'A modern web project.'}\n\n`;

    // Badges
    readme += `![Stars](https://img.shields.io/github/stars/${meta.owner.login}/${meta.name}) `;
    readme += `![Forks](https://img.shields.io/github/forks/${meta.owner.login}/${meta.name})\n\n`;

    // Features
    readme += `## 🚀 Features\n`;
    readme += `- Fast and responsive\n- Easy to customize\n- Modern tech stack\n\n`;

    // Installation
    if (packageJson) {
        readme += `## 📦 Installation\n\u0060\u0060\u0060bash\nnpm install ${packageJson.name}\n\u0060\u0060\u0060\n\n`;
    } else {
        readme += `## 📦 Installation\nClone the repo and open in your browser or editor.\n\n`;
    }

    // Usage
    if (packageJson && packageJson.scripts && packageJson.scripts.start) {
        readme += `## 🏃 Usage\n\u0060\u0060\u0060bash\nnpm start\n\u0060\u0060\u0060\n\n`;
    } else {
        readme += `## 🏃 Usage\nOpen \`index.html\` in your browser.\n\n`;
    }

    // Languages
    readme += `## 🛠️ Languages & Tech\n`;
    for (const lang in languages) {
        readme += `- ${lang}\n`;
    }
    readme += `\n`;

    // Contributing
    readme += `## 🤝 Contributing\nContributions, issues and feature requests are welcome!\nFeel free to check [issues page](https://github.com/${meta.owner.login}/${meta.name}/issues).\n\n`;

    // License
    if (meta.license && meta.license.spdx_id) {
        readme += `## 📄 License\n${meta.license.spdx_id}\n`;
    }

    // Footer
    readme += `\n---\nGenerated by [README Generator](https://github.com/dexpie/readmegenerator)\n`;

    return readme;
}
